name: Functional-Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: ianwalter/puppeteer-container@v4.0.0
    - name: Run Tests
      run: |
        npm install
        npm run test
